language: python
sudo: false
notifications:
  email: false
env:
  - TOXENV=py27
  #- TOXENV=py35
  #- TOXENV=py36
  #- TOXENV=py37
  - TOXENV=flake8
install:
  - pip install tox
script: tox
cahce: pip
